"""SHA-256 hashing for the Phase 0 artifact hash manifest.

Used by scripts/hash_manifest.py (to generate/update the manifest) and
scripts/validate_repo.py (to detect drift between the manifest and the
actual file contents). The manifest itself is never included in its own
hash list -- that would be recursive self-hashing.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

# Relative to repo root. Kept as an explicit list (not a glob) so adding a
# new hashed artifact is a deliberate, reviewable change.
PHASE_0_HASHED_ARTIFACTS: list[str] = [
    "configs/architecture/ja150m-v0.1.yaml",
    "configs/architecture/ja150m-v0.1-dense.yaml",
    "docs/research/project-charter.md",
    "docs/research/project-governance.md",
    "docs/architecture/precision-policy.md",
    "docs/research/project-roadmap.md",
    "requirements-lock.txt",
    "juniper_auto/accounting/parameter_count.py",
    "juniper_auto/config/schema.py",
    "juniper_auto/config/frozen.py",
    "scripts/validate_repo.py",
]

# Phase 1 reference-model implementation, training-support, documentation,
# and validator artifacts. Phase 1's approval and recovery records are
# protected because they contain the evidence and limitations on which the
# approval tag relies. The artifact-hash manifests themselves remain excluded
# to avoid recursive self-hashing.
PHASE_1_HASHED_ARTIFACTS: list[str] = [
    "juniper_auto/model/__init__.py",
    "juniper_auto/model/norm.py",
    "juniper_auto/model/rope.py",
    "juniper_auto/model/attention.py",
    "juniper_auto/model/ffn.py",
    "juniper_auto/model/moe.py",
    "juniper_auto/model/block.py",
    "juniper_auto/model/losses.py",
    "juniper_auto/model/model.py",
    "juniper_auto/model/inspection.py",
    "juniper_auto/training/__init__.py",
    "juniper_auto/training/state.py",
    "juniper_auto/training/checkpoint.py",
    "juniper_auto/training/tiny_overfit.py",
    "juniper_auto/training/profiling.py",
    "docs/adr/0008-moe-auxiliary-loss-semantics.md",
    "docs/architecture/reference-model-implementation.md",
    "docs/phases/phase-1-architecture.md",
    "docs/phases/phase-1-requirements-traceability.md",
    "docs/phases/phase-1-sonnet-self-review.md",
    "docs/phases/phase-1-sol-independent-review.md",
    "docs/recovery/phase-1.md",
    "docs/time/phase-hours.csv",
    "scripts/validate_phase1.py",
    "scripts/run_phase1_experiment.py",
    "experiments/registry.yaml",
    "docs/experiments/results/exp-0003-param-verification.json",
    "docs/experiments/results/exp-0004-dense-tiny-overfit.json",
    "docs/experiments/results/exp-0005-sparse-tiny-overfit.json",
    "docs/experiments/results/exp-0006-checkpoint-resume-equivalence.json",
    "docs/experiments/results/exp-0007-flowbox-dense-profile.json",
    "docs/experiments/results/exp-0008-flowbox-sparse-profile.json",
    "docs/experiments/results/exp-0009-sol-param-verification.json",
    "docs/experiments/results/exp-0010-sol-dense-tiny-overfit.json",
    "docs/experiments/results/exp-0011-sol-sparse-tiny-overfit.json",
    "docs/experiments/results/exp-0012-sol-resume-equivalence.json",
    "docs/experiments/results/exp-0013-sol-flowbox-dense-profile.json",
    "docs/experiments/results/exp-0014-sol-flowbox-sparse-profile.json",
    "manifests/phase-1-test-manifest.yaml",
]

# Phase 1 test files covered by manifests/phase-1-test-manifest.yaml
# (generated by scripts/generate_phase1_test_manifest.py). Listed
# explicitly, not globbed, so adding a new test file to this protected set
# is a deliberate, reviewable change.
PHASE_1_TEST_FILES: list[str] = [
    "tests/model_fixtures.py",
    "tests/test_model_norm.py",
    "tests/test_model_rope.py",
    "tests/test_model_ffn.py",
    "tests/test_model_attention.py",
    "tests/test_model_moe.py",
    "tests/test_model_losses.py",
    "tests/test_model_shapes.py",
    "tests/test_model_causality_padding.py",
    "tests/test_model_official_architecture.py",
    "tests/test_model_initialization.py",
    "tests/test_model_gradients.py",
    "tests/test_model_optimizer.py",
    "tests/test_model_serialization.py",
    "tests/test_model_activation_checkpointing.py",
    "tests/test_model_fault_injection.py",
    "tests/test_training_state.py",
    "tests/test_training_checkpoint.py",
    "tests/test_training_tiny_overfit.py",
    "tests/test_training_resume_equivalence.py",
    "tests/test_training_profiling.py",
    "tests/test_experiment_provenance.py",
    "tests/test_phase_report_structure.py",
]


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def compute_hashes(repo_root: Path, relative_paths: list[str] = PHASE_0_HASHED_ARTIFACTS) -> dict[str, str]:
    result = {}
    for rel in relative_paths:
        full = repo_root / rel
        if not full.is_file():
            raise FileNotFoundError(f"artifact listed for hashing does not exist: {rel}")
        result[rel] = sha256_file(full)
    return result
