"""SHA-256 hashing for the Phase 0 artifact hash manifest.

Used by scripts/hash_manifest.py (to generate/update the manifest) and
scripts/validate_repo.py (to detect drift between the manifest and the
actual file contents). The manifest itself is never included in its own
hash list -- that would be recursive self-hashing.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

# Relative to repo root. Kept as an explicit list (not a glob) so adding a
# new hashed artifact is a deliberate, reviewable change.
PHASE_0_HASHED_ARTIFACTS: list[str] = [
    "configs/architecture/ja150m-v0.1.yaml",
    "configs/architecture/ja150m-v0.1-dense.yaml",
    "docs/research/project-charter.md",
    "docs/research/project-governance.md",
    "docs/architecture/precision-policy.md",
    "docs/research/project-roadmap.md",
    "requirements-lock.txt",
    "juniper_auto/accounting/parameter_count.py",
    "juniper_auto/config/schema.py",
    "juniper_auto/config/frozen.py",
    "scripts/validate_repo.py",
]

# Phase 1 reference-model implementation, training-support, documentation,
# and validator artifacts. Phase 1's approval and recovery records are
# protected because they contain the evidence and limitations on which the
# approval tag relies. The artifact-hash manifests themselves remain excluded
# to avoid recursive self-hashing.
PHASE_1_HASHED_ARTIFACTS: list[str] = [
    "juniper_auto/model/__init__.py",
    "juniper_auto/model/norm.py",
    "juniper_auto/model/rope.py",
    "juniper_auto/model/attention.py",
    "juniper_auto/model/ffn.py",
    "juniper_auto/model/moe.py",
    "juniper_auto/model/block.py",
    "juniper_auto/model/losses.py",
    "juniper_auto/model/model.py",
    "juniper_auto/model/inspection.py",
    "juniper_auto/training/__init__.py",
    "juniper_auto/training/state.py",
    "juniper_auto/training/checkpoint.py",
    "juniper_auto/training/tiny_overfit.py",
    "juniper_auto/training/profiling.py",
    "docs/adr/0008-moe-auxiliary-loss-semantics.md",
    "docs/architecture/reference-model-implementation.md",
    "docs/phases/phase-1-architecture.md",
    "docs/phases/phase-1-requirements-traceability.md",
    "docs/phases/phase-1-sonnet-self-review.md",
    "docs/phases/phase-1-sol-independent-review.md",
    "docs/recovery/phase-1.md",
    "docs/time/phase-hours.csv",
    "scripts/validate_phase1.py",
    "scripts/run_phase1_experiment.py",
    "experiments/registry.yaml",
    "docs/experiments/results/exp-0003-param-verification.json",
    "docs/experiments/results/exp-0004-dense-tiny-overfit.json",
    "docs/experiments/results/exp-0005-sparse-tiny-overfit.json",
    "docs/experiments/results/exp-0006-checkpoint-resume-equivalence.json",
    "docs/experiments/results/exp-0007-flowbox-dense-profile.json",
    "docs/experiments/results/exp-0008-flowbox-sparse-profile.json",
    "docs/experiments/results/exp-0009-sol-param-verification.json",
    "docs/experiments/results/exp-0010-sol-dense-tiny-overfit.json",
    "docs/experiments/results/exp-0011-sol-sparse-tiny-overfit.json",
    "docs/experiments/results/exp-0012-sol-resume-equivalence.json",
    "docs/experiments/results/exp-0013-sol-flowbox-dense-profile.json",
    "docs/experiments/results/exp-0014-sol-flowbox-sparse-profile.json",
    "manifests/phase-1-test-manifest.yaml",
]

# Phase 1 test files covered by manifests/phase-1-test-manifest.yaml
# (generated by scripts/generate_phase1_test_manifest.py). Listed
# explicitly, not globbed, so adding a new test file to this protected set
# is a deliberate, reviewable change.
PHASE_1_TEST_FILES: list[str] = [
    "tests/model_fixtures.py",
    "tests/test_model_norm.py",
    "tests/test_model_rope.py",
    "tests/test_model_ffn.py",
    "tests/test_model_attention.py",
    "tests/test_model_moe.py",
    "tests/test_model_losses.py",
    "tests/test_model_shapes.py",
    "tests/test_model_causality_padding.py",
    "tests/test_model_official_architecture.py",
    "tests/test_model_initialization.py",
    "tests/test_model_gradients.py",
    "tests/test_model_optimizer.py",
    "tests/test_model_serialization.py",
    "tests/test_model_activation_checkpointing.py",
    "tests/test_model_fault_injection.py",
    "tests/test_training_state.py",
    "tests/test_training_checkpoint.py",
    "tests/test_training_tiny_overfit.py",
    "tests/test_training_resume_equivalence.py",
    "tests/test_training_profiling.py",
    "tests/test_experiment_provenance.py",
    "tests/test_phase_report_structure.py",
]


# Phase 2 sparse-routing/diagnostics/ablation implementation, the
# context-sensitivity analysis package, documentation, validator, and
# executed-experiment artifacts. Several files also appear in
# PHASE_1_HASHED_ARTIFACTS (juniper_auto/model/moe.py, block.py, model.py,
# docs/time/phase-hours.csv, experiments/registry.yaml) -- each phase's
# manifest independently records that file's hash as of when THAT phase's
# evidence was finalized; Phase 1's manifest is regenerated at the end of
# Phase 2 engineering to match the post-Phase-2 content of the few files
# that legitimately continue to evolve (time accounting, the experiment
# registry) or that Phase 2 explicitly refactored under a proven-equivalent
# contract (moe.py -- see docs/adr/0009-moe-dispatch-backend-selection.md
# and the golden bit-exact comparison in tests/test_model_moe_dispatch.py,
# which reads the approved Phase 1 commit directly from the immutable
# `phase-1-architecture` git tag rather than from this hash manifest, and so
# is unaffected by Phase 1's manifest being regenerated).
PHASE_2_HASHED_ARTIFACTS: list[str] = [
    ".github/workflows/phase-2-validation.yml",
    ".github/workflows/phase-0-validation.yml",
    ".github/workflows/phase-1-validation.yml",
    "README.md",
    "juniper_auto/model/routing.py",
    "juniper_auto/model/moe_dispatch.py",
    "juniper_auto/model/moe_ablations.py",
    "juniper_auto/model/moe_diagnostics.py",
    "juniper_auto/model/moe.py",
    "juniper_auto/model/block.py",
    "juniper_auto/model/model.py",
    "juniper_auto/analysis/__init__.py",
    "juniper_auto/analysis/context_sensitivity.py",
    "docs/adr/0009-moe-dispatch-backend-selection.md",
    "docs/architecture/moe-routing-diagnostics.md",
    "docs/phases/phase-2-moe.md",
    "docs/phases/phase-2-requirements-traceability.md",
    "docs/phases/phase-2-sonnet-self-review.md",
    "docs/phases/phase-2-sol-independent-review.md",
    "docs/recovery/phase-2.md",
    "docs/time/phase-hours.csv",
    "scripts/validate_phase2.py",
    "scripts/run_phase2_experiment.py",
    "scripts/generate_phase2_test_manifest.py",
    "experiments/registry.yaml",
    "docs/experiments/results/exp-0015-moe-reference-optimized-equivalence.json",
    "docs/experiments/results/exp-0016-official-model-routing-trace.json",
    "docs/experiments/results/exp-0016-official-model-routing-trace.trace.json",
    "docs/experiments/results/exp-0017-context-sensitivity-untrained-baseline.json",
    "docs/experiments/results/exp-0018-routing-health-detector-validation.json",
    "docs/experiments/results/exp-0019-ablation-validation.json",
    "docs/experiments/results/exp-0020-reproducibility.json",
    "docs/experiments/results/exp-0021-flowbox-moe-dispatch-profile.json",
    "docs/experiments/results/exp-0022-sol-reference-optimized-equivalence.json",
    "docs/experiments/results/exp-0023-sol-independent-diagnostic-demonstration.json",
    "docs/experiments/results/exp-0023-sol-independent-diagnostic-demonstration.trace.json",
    "manifests/phase-2-test-manifest.yaml",
]

# Phase 2 test files covered by manifests/phase-2-test-manifest.yaml
# (generated by scripts/generate_phase2_test_manifest.py). tests/model_fixtures.py
# and tests/test_model_fault_injection.py also appear in PHASE_1_TEST_FILES --
# same reasoning as above.
PHASE_2_TEST_FILES: list[str] = [
    "tests/test_model_moe_dispatch.py",
    "tests/test_model_moe_property.py",
    "tests/test_model_moe_diagnostics.py",
    "tests/test_model_moe_ablations.py",
    "tests/test_model_moe_trace.py",
    "tests/test_context_sensitivity.py",
    "tests/test_model_fault_injection.py",
    "tests/test_phase_report_structure.py",
    "tests/test_experiment_registry.py",
]


# Phase 3 unified-tokenizer implementation, frozen artifact, corpus manifest,
# held-out evaluation fixture, scripts, documentation, ADRs, validator, and
# executed-experiment artifacts. As in Phase 2, a few globally-evolving files
# (docs/time/phase-hours.csv, experiments/registry.yaml, README.md) also
# appear in earlier phases' lists; those earlier manifests are regenerated at
# the end of Phase 3 engineering to match the post-Phase-3 content of exactly
# those files. The approved Phase 0/1/2 states remain pinned by their
# immutable git tags (phase-0-foundation / phase-1-architecture /
# phase-2-moe), not by these mutable manifests. The individual corpus shards
# are NOT listed here on purpose: corpus-manifest.json records every shard's
# SHA-256 and scripts/validate_phase3.py re-verifies each shard against it, so
# hashing the manifest transitively protects the whole corpus without a broad
# directory glob.
PHASE_3_HASHED_ARTIFACTS: list[str] = [
    "juniper_auto/tokenizer/__init__.py",
    "juniper_auto/tokenizer/constants.py",
    "juniper_auto/tokenizer/bytelevel.py",
    "juniper_auto/tokenizer/bpe.py",
    "juniper_auto/tokenizer/tokenizer.py",
    "juniper_auto/tokenizer/artifacts.py",
    "juniper_auto/tokenizer/corpus.py",
    "juniper_auto/tokenizer/train.py",
    "juniper_auto/tokenizer/evaluation.py",
    "juniper_auto/tokenizer/comparators.py",
    "juniper_auto/tokenizer/config.py",
    "configs/tokenizer/ja-tokenizer-v0.1.yaml",
    "manifests/frozen-artifacts.yaml",
    "data/tokenizer/ja-tokenizer-v0.1/tokenizer.json",
    "data/tokenizer/ja-tokenizer-v0.1/vocab.json",
    "data/tokenizer/ja-tokenizer-v0.1/merges.txt",
    "data/tokenizer/ja-tokenizer-v0.1/special_tokens.json",
    "data/tokenizer/ja-tokenizer-v0.1/tokenizer_config.json",
    "data/tokenizer/ja-tokenizer-v0.1/hashes.json",
    "data/tokenizer/corpus/corpus-manifest.json",
    "data/tokenizer/eval/held-out-eval-fixture.json",
    "scripts/build_tokenizer_corpus.py",
    "scripts/build_tokenizer_eval_fixture.py",
    "scripts/train_tokenizer.py",
    "scripts/run_phase3_experiment.py",
    "scripts/validate_phase3.py",
    "scripts/generate_phase3_test_manifest.py",
    ".github/workflows/phase-3-validation.yml",
    "docs/architecture/tokenizer-design.md",
    "docs/adr/0010-tokenizer-implementation-choice.md",
    "docs/adr/0011-tokenizer-special-token-and-reserved-id-layout.md",
    "docs/adr/0012-tokenizer-normalization-and-pretokenization-policy.md",
    "docs/phases/phase-3-tokenizer.md",
    "docs/phases/phase-3-requirements-traceability.md",
    "docs/phases/phase-3-sonnet-self-review.md",
    "docs/recovery/phase-3.md",
    "docs/time/phase-hours.csv",
    "experiments/registry.yaml",
    "docs/experiments/results/exp-0024-tokenizer-rebuild-determinism.json",
    "docs/experiments/results/exp-0025-tokenizer-roundtrip-fallback.json",
    "docs/experiments/results/exp-0026-tokenizer-efficiency.json",
    "docs/experiments/results/exp-0027-tokenizer-baseline-comparison.json",
    "docs/experiments/results/exp-0028-tokenizer-control-and-reserved.json",
    "docs/experiments/results/exp-0029-tokenizer-flowbox-performance.json",
    "docs/experiments/results/exp-0030-tokenizer-difficult-examples.json",
    "manifests/phase-3-test-manifest.yaml",
]

PHASE_3_TEST_FILES: list[str] = [
    "tests/tokenizer_fixtures.py",
    "tests/test_tokenizer_vocab.py",
    "tests/test_tokenizer_roundtrip.py",
    "tests/test_tokenizer_normalization.py",
    "tests/test_tokenizer_determinism.py",
    "tests/test_tokenizer_control_tokens.py",
    "tests/test_tokenizer_failure_handling.py",
    "tests/test_tokenizer_fault_injection.py",
    "tests/test_tokenizer_config_and_model.py",
    "tests/test_tokenizer_evaluation.py",
]


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def compute_hashes(repo_root: Path, relative_paths: list[str] = PHASE_0_HASHED_ARTIFACTS) -> dict[str, str]:
    result = {}
    for rel in relative_paths:
        full = repo_root / rel
        if not full.is_file():
            raise FileNotFoundError(f"artifact listed for hashing does not exist: {rel}")
        result[rel] = sha256_file(full)
    return result
