#!/usr/bin/env python3
"""Generate/update manifests/phase-3-test-manifest.yaml -- a per-file
SHA-256 record of the Phase 3 test files listed in
juniper_auto.util.hashing.PHASE_3_TEST_FILES.

This manifest is itself one of the entries in
juniper_auto.util.hashing.PHASE_3_HASHED_ARTIFACTS, so run this script
BEFORE scripts/hash_manifest.py --phase 3 whenever a Phase 3 test file
changes.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import yaml  # noqa: E402

from juniper_auto.util.hashing import PHASE_3_TEST_FILES, compute_hashes  # noqa: E402


def main() -> int:
    hashes = compute_hashes(REPO_ROOT, PHASE_3_TEST_FILES)
    manifest = {
        "algorithm": "sha256",
        "generated_by": "scripts/generate_phase3_test_manifest.py",
        "sha256": dict(sorted(hashes.items())),
    }
    out_path = REPO_ROOT / "manifests" / "phase-3-test-manifest.yaml"
    with out_path.open("w", encoding="utf-8") as f:
        f.write(
            "# Phase 3 test-file manifest -- generated by scripts/generate_phase3_test_manifest.py.\n"
            "# Do not hand-edit; regenerate after adding/changing a Phase 3 test file, then\n"
            "# regenerate manifests/phase-3-artifact-hashes.yaml (this file is itself one of\n"
            "# its hashed entries).\n"
        )
        yaml.safe_dump(manifest, f, sort_keys=False, default_flow_style=False)
    print(f"wrote {len(hashes)} hashes to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
