#!/usr/bin/env python3
"""Generate/update manifests/phase-0-artifact-hashes.yaml from the current
contents of the files listed in juniper_auto.util.hashing.PHASE_0_HASHED_ARTIFACTS.

Run this whenever one of those files changes, then commit the regenerated
manifest in the same change. scripts/validate_repo.py's "artifact hashes"
gate will fail if the manifest goes stale relative to the actual files.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import yaml  # noqa: E402

from juniper_auto.util.hashing import compute_hashes  # noqa: E402


def main() -> int:
    hashes = compute_hashes(REPO_ROOT)
    manifest = {
        "algorithm": "sha256",
        "generated_by": "scripts/hash_manifest.py",
        "sha256": dict(sorted(hashes.items())),
    }
    out_path = REPO_ROOT / "manifests" / "phase-0-artifact-hashes.yaml"
    with out_path.open("w", encoding="utf-8") as f:
        f.write(
            "# Phase 0 artifact hash manifest -- generated by scripts/hash_manifest.py.\n"
            "# Do not hand-edit; regenerate after changing a listed artifact.\n"
            "# This manifest is deliberately excluded from its own hash list\n"
            "# (no recursive self-hashing).\n"
        )
        yaml.safe_dump(manifest, f, sort_keys=False, default_flow_style=False)
    print(f"wrote {len(hashes)} hashes to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
