#!/usr/bin/env python3
"""Generate/update the artifact hash manifest for a given phase.

    python scripts/hash_manifest.py --phase 0   # manifests/phase-0-artifact-hashes.yaml (default)
    python scripts/hash_manifest.py --phase 1   # manifests/phase-1-artifact-hashes.yaml

Run this whenever a hashed artifact for that phase changes, then commit
the regenerated manifest in the same change. scripts/validate_repo.py's
(Phase 0) and scripts/validate_phase1.py's (Phase 1) "artifact hashes"
gates fail if a manifest goes stale relative to the actual files. For
Phase 1, run scripts/generate_phase1_test_manifest.py first if a Phase 1
test file changed -- that manifest is itself one of Phase 1's hashed
artifacts.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import yaml  # noqa: E402

from juniper_auto.util.hashing import (  # noqa: E402
    PHASE_0_HASHED_ARTIFACTS,
    PHASE_1_HASHED_ARTIFACTS,
    compute_hashes,
)

PHASES = {
    0: (PHASE_0_HASHED_ARTIFACTS, "manifests/phase-0-artifact-hashes.yaml", "Phase 0"),
    1: (PHASE_1_HASHED_ARTIFACTS, "manifests/phase-1-artifact-hashes.yaml", "Phase 1"),
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--phase", type=int, choices=sorted(PHASES), default=0)
    args = parser.parse_args()

    artifacts, manifest_rel_path, label = PHASES[args.phase]
    hashes = compute_hashes(REPO_ROOT, artifacts)
    manifest = {
        "algorithm": "sha256",
        "generated_by": "scripts/hash_manifest.py",
        "sha256": dict(sorted(hashes.items())),
    }
    out_path = REPO_ROOT / manifest_rel_path
    with out_path.open("w", encoding="utf-8") as f:
        f.write(
            f"# {label} artifact hash manifest -- generated by scripts/hash_manifest.py --phase {args.phase}.\n"
            "# Do not hand-edit; regenerate after changing a listed artifact.\n"
            "# This manifest is deliberately excluded from its own hash list\n"
            "# (no recursive self-hashing).\n"
        )
        yaml.safe_dump(manifest, f, sort_keys=False, default_flow_style=False)
    print(f"wrote {len(hashes)} hashes to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
